# Configuration file for golangci-lint
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
  disable:
    # Temporarily disable these linters until we can fix them
    - errcheck
    - unused
    - misspell

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - comando
      - comandos
      - organizacional
      - Organizacional
      - Convers
      - convers
      - operacional
      - corporativos
      - presentes
      - condicional
      - problemas

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude issues temporarily
  exclude-rules:
    - path: ".*"
      linters:
        - errcheck
      text: "Error return value of `d.Set` is not checked"
    - path: ".*"
      linters:
        - errcheck
      text: "Error return value of .* is not checked"

# Output configuration
output:
  sort-results: true 